'use client';
import Link from 'next/link';
import { useParams } from 'next/navigation';
import { useState } from 'react';
import Layout from '@/components/Layout';
import { calculatePathwayReadiness, deriveSparkLifecycle } from '@/lib/logic';
import { useStore } from '@/components/store';

type AnalysisPathway = { title: string; outputType: string; reason: string; suggestedNextMove: string };
type AnalysisResult = { summary: string; suggestedKind: string; suggestedBranchName: string; suggestedStage: 'Spark'|'Ember'|'Fire'|'Blaze'; suggestedValueTags: string[]; suggestedPathways: AnalysisPathway[]; suggestedNextMove: string; confidenceNotes: string; usedFallback?: boolean };

export default function SparkDetailPage() {
  const { id } = useParams<{ id: string }>();
  const { branches, sparks, attachments, pathways, blazes, actions, addPathway, updatePathway, releaseBlaze, activateFire, freezeSpark, updateSpark, addSparkAttachments, removeSparkAttachment, addActionLog } = useStore();
  const [feedback, setFeedback] = useState('');
  const [lane, setLane] = useState(''); const [nextMoveInput, setNextMoveInput] = useState('');
  const [analysis, setAnalysis] = useState<AnalysisResult | null>(null); const [analysisLoading, setAnalysisLoading] = useState(false); const [analysisError, setAnalysisError] = useState(''); const [pathwayDrafts, setPathwayDrafts] = useState<Record<number, string>>({}); const [nextMoveDraft, setNextMoveDraft] = useState('');
  const [branchSelection, setBranchSelection] = useState('');
  const [outputTitle, setOutputTitle] = useState(''); const [outputType, setOutputType] = useState('song'); const [releasePathwayId, setReleasePathwayId] = useState(''); const [releaseNotes, setReleaseNotes] = useState('');
  const spark = sparks.find((s) => s.id === id);
  if (!spark) return <Layout><p>Asset not found. <Link href='/vault' className='text-neon'>Back</Link></p></Layout>;
  const routes = pathways.filter((p) => p.sparkId === id); const sparkBlazes = blazes.filter((b) => b.sparkId === id); const branch = branches.find((b) => b.id === spark.branchId);
  const sparkAttachments = attachments.filter((a)=>a.sparkId===spark.id);
  const lifecycle = deriveSparkLifecycle(spark, pathways, blazes);
  const hasChosenPathway = routes.some((r) => r.status === 'chosen' || r.status === 'active' || r.status === 'completed');
  const primaryCommand = sparkBlazes.length ? { label: 'Released. Add another output when ready.', detail: 'This asset has reached Blaze. Continue publishing from Fire pathways.' } : hasChosenPathway && spark.nextMove ? { label: 'Activate as Fire', detail: 'Chosen pathway + next move are ready to activate.' } : hasChosenPathway ? { label: 'Set Next Move', detail: 'Define the next physical action to move from Ember to Fire.' } : { label: 'Create or accept a pathway', detail: 'Route this asset into at least one output lane to move from Spark to Ember.' };

  const analyzeSpark = async () => { setAnalysisLoading(true); setAnalysisError(''); try { const res = await fetch('/api/analyze-spark', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ title: spark.title, kind: spark.kind, notes: spark.notes, branchName: branch?.name, attachments: sparkAttachments.map((a) => ({ fileName: a.name, mimeType: a.mimeType, attachmentType: a.type, size: a.size })), existingPathways: routes.map((r) => ({ title: r.title, outputType: r.outputType })), existingNextMove: spark.nextMove }) }); if (!res.ok) throw new Error('Request failed'); const data = (await res.json()) as AnalysisResult; setAnalysis(data); setNextMoveDraft(data.suggestedNextMove || ''); setPathwayDrafts(Object.fromEntries((data.suggestedPathways || []).map((p, i) => [i, p.title]))); setBranchSelection(''); } catch { setAnalysisError('Could not analyze asset right now. Try again.'); } finally { setAnalysisLoading(false); } };

  return <Layout><h2 className='text-xl font-semibold'>Spark Command Hub</h2>
    <section className='mt-3 rounded-xl border border-neon/40 bg-panelAlt/85 p-4'>
      <h3 className='text-sm uppercase text-neonDim'>Asset Preview / Identity</h3>
      <h4 className='mt-2 text-lg font-semibold'>{spark.title}</h4><p className='text-xs text-muted'>{spark.kind} • {branch?.name ?? spark.branchId}</p>
      <dl className='mt-2 grid grid-cols-2 gap-2 text-sm'><div><dt className='text-muted'>Lifecycle state</dt><dd>{lifecycle.stage}</dd></div><div><dt className='text-muted'>Status</dt><dd>{spark.status}</dd></div><div><dt className='text-muted'>What could it become?</dt><dd>{routes.length ? routes.map((r)=>r.title).join(', ') : 'No pathway chosen yet'}</dd></div><div><dt className='text-muted'>Next Physical Move</dt><dd>{spark.nextMove || 'No next move set yet'}</dd></div></dl>
      <div className='mt-3 grid gap-2 sm:grid-cols-2'>{sparkAttachments.map((att)=><div key={att.id} className='rounded border border-neon/30 p-2 text-xs'><p>{att.name}</p>{att.type==='image'&&att.objectUrl?<img src={att.objectUrl} alt={att.name} className='mt-2 max-h-36 rounded'/>:null}{att.type==='audio'&&att.objectUrl?<audio controls src={att.objectUrl} className='mt-2 w-full'/>:null}{att.type==='video'&&att.objectUrl?<video controls src={att.objectUrl} className='mt-2 max-h-44 w-full rounded'/>:null}</div>)}</div>
    </section>

    <section className='mt-4 rounded-xl border border-neon/40 bg-panelAlt/85 p-4'><h4 className='text-sm uppercase text-neonDim'>Current Command</h4><p className='mt-2 text-sm font-medium'>{primaryCommand.label}</p><p className='text-xs text-neonDim'>{primaryCommand.detail}</p>{feedback?<p className='mt-2 rounded border border-neon/40 p-2 text-xs text-neon'>{feedback}</p>:null}</section>

    <section className='mt-4 rounded-xl border border-neon/40 bg-panelAlt/85 p-4'><h4 className='text-sm uppercase text-neonDim'>Pathways</h4><div className='mt-2 flex gap-2'><input value={lane} onChange={(e)=>setLane(e.target.value)} placeholder='Possible output lane/title' className='flex-1 rounded bg-bg p-2'/><button className='rounded bg-neon px-3 text-bg' onClick={()=>{if(lane.trim()){addPathway(spark.id,lane.trim()); if(lifecycle.stage==='Spark') updateSpark(spark.id,{stage:'Ember',status:spark.status==='frozen'?'frozen':'active'}); setFeedback('Pathway added and visible.'); setLane('');}}}>Add Pathway</button></div><ul className='mt-3 space-y-2'>{routes.length?routes.map((r)=>{const readiness=calculatePathwayReadiness(r,spark,{branches,pathways,blazes});return <li key={r.id} className='rounded border border-neon/40 p-3 text-sm'><p className='font-medium'>{r.title}</p><p className='text-xs text-muted'>Status: {r.status} • Readiness: {readiness.label}</p><div className='mt-2 flex flex-wrap gap-2'><button onClick={()=>{updatePathway(r.id,{status:'chosen'}); updateSpark(spark.id,{stage:sparkBlazes.length?'Blaze':'Ember'}); setFeedback(`Chosen pathway: ${r.title}`);}} className='rounded border border-neon/40 px-2 py-1 text-xs'>Choose Pathway</button><button onClick={()=>{const result = activateFire(spark.id, r.id); if(result.ok){updatePathway(r.id,{status:'active'}); setFeedback(`Activated Fire on ${r.title}.`);} else setFeedback(result.message || 'Could not activate Fire.');}} className='rounded border border-neon/40 px-2 py-1 text-xs'>Activate as Fire</button><button onClick={()=>updatePathway(r.id,{status:'possible'})} className='rounded border border-neon/40 px-2 py-1 text-xs'>Set as Possible</button></div></li>}):<li className='text-sm text-muted'>No pathways yet.</li>}</ul></section>

    <section className='mt-4 rounded-xl border border-neon/40 bg-panelAlt/85 p-4'><h4 className='text-sm uppercase text-neonDim'>Next Move Command</h4><div className='mt-2 flex gap-2'><input value={nextMoveInput} onChange={(e)=>setNextMoveInput(e.target.value)} placeholder='Record rough vocals / Clean linework / Export print file...' className='flex-1 rounded bg-bg p-2'/><button className='rounded bg-neon px-3 text-bg' onClick={()=>{if(nextMoveInput.trim()){updateSpark(spark.id,{nextMove:nextMoveInput.trim()}); setFeedback(`Set Next Move: ${nextMoveInput.trim()}`); setNextMoveInput('');}}}>Set Next Move</button><button onClick={()=>freezeSpark(spark.id)} className='rounded border border-neon/40 px-3'>Freeze</button></div></section>

    {analysis?<section className='mt-4 rounded-xl border border-neon/40 bg-panelAlt/85 p-4'><h4 className='text-sm uppercase text-neonDim'>AI Interpretation</h4><p className='mt-2 text-sm'>{analysis.summary}</p><div className='mt-3'><p className='text-xs uppercase text-neonDim'>Suggested Branch</p><div className='mt-1 flex gap-2'><select value={branchSelection} onChange={(e)=>setBranchSelection(e.target.value)} className='rounded bg-bg p-1 text-xs'><option value=''>Choose branch</option>{branches.map((b)=><option key={b.id} value={b.id}>{b.name}</option>)}</select><button onClick={()=>{if(branchSelection){updateSpark(spark.id,{branchId:branchSelection}); setFeedback('Applied existing branch.');}}} className='rounded border border-neon/40 px-2 py-1 text-xs'>Apply Existing Branch</button></div></div>
      <ul className='mt-3 space-y-2'>{analysis.suggestedPathways.map((p,idx)=><li key={idx} className='rounded border border-neon/30 p-2 text-sm'><input value={pathwayDrafts[idx] ?? p.title} onChange={(e)=>setPathwayDrafts((s)=>({...s,[idx]:e.target.value}))} className='w-full rounded bg-bg p-2 text-sm'/><button onClick={()=>{const title=(pathwayDrafts[idx] ?? p.title).trim(); if(title){addPathway(spark.id,title,{outputType:p.outputType,nextMove:p.suggestedNextMove}); updateSpark(spark.id,{stage:spark.stage==='Spark'?'Ember':spark.stage,status:spark.status==='frozen'?'frozen':'active'}); addActionLog('create_pathway',`Accepted AI Pathway: ${title}`,true,{sparkId:spark.id,branchId:spark.branchId}); setPathwayDrafts((s)=>({...s,[idx]:`${title} (Accepted)`})); setFeedback(`Accepted AI Pathway: ${title}`);}}} className='mt-2 rounded border border-neon/40 px-2 py-1 text-xs'>Accept Pathway</button></li>)}</ul>
      <div className='mt-3 flex gap-2'><input value={nextMoveDraft} onChange={(e)=>setNextMoveDraft(e.target.value)} className='flex-1 rounded bg-bg p-2 text-sm'/><button onClick={()=>{if(nextMoveDraft.trim()){updateSpark(spark.id,{nextMove:nextMoveDraft.trim()}); addActionLog('set_next_move',`Accepted AI Next Move: ${nextMoveDraft.trim()}`,true,{sparkId:spark.id,branchId:spark.branchId}); setFeedback(`Accepted AI Next Move: ${nextMoveDraft.trim()}`);}}} className='rounded border border-neon/40 px-2 py-1 text-xs'>Accept Next Move</button></div>
    </section>:<section className='mt-4 rounded-xl border border-neon/40 bg-panelAlt/85 p-4'><div className='flex items-center justify-between'><h4 className='text-sm uppercase text-neonDim'>AI Interpretation</h4><button onClick={analyzeSpark} disabled={analysisLoading} className='rounded bg-neon px-3 py-1 text-xs text-bg disabled:opacity-60'>{analysisLoading ? 'Analyzing…' : 'Analyze Asset'}</button></div>{analysisError?<p className='mt-2 text-sm text-red-300'>{analysisError}</p>:<p className='mt-2 text-xs text-muted'>Run analysis to generate editable pathways and next moves.</p>}</section>}

    <section className='mt-4 rounded-xl border border-neon/40 bg-panelAlt/85 p-4'><h4 className='text-sm uppercase text-neonDim'>Release Blaze</h4><div className='mt-2 grid gap-2 sm:grid-cols-2'><input value={outputTitle} onChange={(e)=>setOutputTitle(e.target.value)} placeholder='Output title' className='rounded bg-bg p-2'/><input value={outputType} onChange={(e)=>setOutputType(e.target.value)} placeholder='song/reel/post/tattoo/print...' className='rounded bg-bg p-2'/><select value={releasePathwayId} onChange={(e)=>setReleasePathwayId(e.target.value)} className='rounded bg-bg p-2'><option value=''>Related pathway (optional)</option>{routes.map((r)=><option key={r.id} value={r.id}>{r.title}</option>)}</select><input value={releaseNotes} onChange={(e)=>setReleaseNotes(e.target.value)} placeholder='Optional notes' className='rounded bg-bg p-2'/><button className='rounded bg-neon px-3 py-2 text-bg' onClick={()=>{if(outputTitle.trim()&&outputType.trim()){releaseBlaze(spark.id,outputTitle.trim(),outputType.trim(),releasePathwayId || undefined, releaseNotes.trim() || undefined); setFeedback(`Released Blaze: ${outputTitle.trim()}`); setOutputTitle('');}}}>Release Blaze</button></div></section>

    {sparkBlazes.length ? <section className='mt-4 rounded-xl border border-neon/40 bg-panelAlt/85 p-4'><h4 className='text-sm uppercase text-neonDim'>Released Outputs</h4><ul className='mt-2 space-y-2 text-sm'>{sparkBlazes.map((b)=><li key={b.id} className='rounded border border-neon/30 p-2'><p className='font-medium'>{b.title}</p><p className='text-xs text-muted'>{b.outputType} • {b.releasedAt}</p><p className='text-xs text-neonDim'>Pathway: {routes.find((r)=>r.id===b.pathwayId)?.title || 'Not linked'}</p>{b.notes?<p className='text-xs'>{b.notes}</p>:null}</li>)}</ul></section> : null}

    <details className='mt-4 rounded-xl border border-neon/40 bg-panelAlt/85 p-4'><summary className='cursor-pointer text-sm uppercase text-neonDim'>History</summary><ul className='mt-2 text-sm'>{actions.filter((a) => a.sparkId === spark.id).slice(0,12).map((a)=><li key={a.id}>{a.date} • {a.action}</li>)}</ul></details>
    <section className='mt-4 rounded-xl border border-neon/40 bg-panelAlt/85 p-4'><h4 className='text-sm uppercase text-neonDim'>Attachments</h4><input type='file' onChange={(e)=>{const f=e.target.files?.[0]; if(!f)return; const t=f.type.startsWith('image/')?'image':f.type.startsWith('audio/')?'audio':f.type.startsWith('video/')?'video':'file'; addSparkAttachments(spark.id,[{name:f.name,type:t as any,mimeType:f.type,size:f.size,objectUrl:URL.createObjectURL(f)}]);}} className='mt-2 text-sm'/><div className='mt-2 space-y-2'>{sparkAttachments.map((att)=><button key={att.id} onClick={()=>removeSparkAttachment(att.id)} className='rounded border border-neon/40 px-2 py-1 text-xs'>Remove {att.name}</button>)}</div></section>
  </Layout>;
}
