'use client';
import Link from 'next/link';
import { useParams } from 'next/navigation';
import { useMemo, useState } from 'react';
import Layout from '@/components/Layout';
import { calculateHeatSignal, calculatePathwayReadiness, deriveSparkLifecycle } from '@/lib/logic';
import { useStore } from '@/components/store';

export default function SparkDetailPage() {
  const { id } = useParams<{ id: string }>();
  const { branches, sparks, attachments, pathways, blazes, actions, addPathway, updatePathway, releaseBlaze, routeSpark, activateFire, freezeSpark, updateSpark, addSparkAttachments, removeSparkAttachment } = useStore();
  const [lane, setLane] = useState(''); const [nextMoveInput, setNextMoveInput] = useState(''); const [editing, setEditing] = useState(false);
  const [routeOpen, setRouteOpen] = useState(false); const [routeType, setRouteType] = useState(''); const [routePathway, setRoutePathway] = useState(''); const [routeValueTags, setRouteValueTags] = useState(''); const [outputTitle, setOutputTitle] = useState(''); const [outputType, setOutputType] = useState('song'); const [releasePathwayId, setReleasePathwayId] = useState(''); const [releaseNotes, setReleaseNotes] = useState(''); const [feedback, setFeedback] = useState(''); const [draft, setDraft] = useState({ title: '', kind: '', branchId: '', notes: '', nextMove: '', status: 'new', stage: 'Spark' });
  const spark = sparks.find((s) => s.id === id);
  if (!spark) return <Layout><p>Spark not found. <Link href='/vault' className='text-neon'>Back</Link></p></Layout>;
  const routes = pathways.filter((p) => p.sparkId === id); const sparkBlazes = blazes.filter((b) => b.sparkId === id); const branch = branches.find((b) => b.id === spark.branchId);
  const heat = calculateHeatSignal(spark, { branches, pathways, blazes });

  const sparkAttachments = attachments.filter((a)=>a.sparkId===spark.id);
  const startEdit = () => { setDraft({ title: spark.title, kind: spark.kind, branchId: spark.branchId, notes: spark.notes ?? '', nextMove: spark.nextMove ?? '', status: spark.status, stage: spark.stage }); setEditing(true); };
  const lifecycle = deriveSparkLifecycle(spark, pathways, blazes); const diagnosis = lifecycle.reason;

  const stageActions = spark.stage === 'Spark' ? [<button key='route' onClick={()=>{setRouteOpen((x)=>!x);setFeedback('Spark routed to Ember.');}} className='rounded border border-neon/40 bg-bg px-3 py-1 text-sm'>Route Spark</button>, <button key='freeze' onClick={()=>freezeSpark(spark.id)} className='rounded border border-neon/40 bg-bg px-3 py-1 text-sm'>Freeze</button>] : spark.stage === 'Ember' ? [<button key='pathway' onClick={()=>setFeedback('Add or choose a pathway below.')} className='rounded border border-neon/40 bg-bg px-3 py-1 text-sm'>Add/Choose Pathway</button>, ...(routes.length?[<button key='fire' onClick={()=>{routes[0] ? activateFire(spark.id, routes[0].id) : { ok: false };setFeedback('Fire activated.');}} className='rounded border border-neon/40 bg-bg px-3 py-1 text-sm'>Activate Fire</button>]:[]), <button key='freeze' onClick={()=>freezeSpark(spark.id)} className='rounded border border-neon/40 bg-bg px-3 py-1 text-sm'>Freeze</button>] : spark.stage === 'Fire' ? [<button key='setmove' onClick={()=>setFeedback('Set or update next move below.')} className='rounded border border-neon/40 bg-bg px-3 py-1 text-sm'>Set/Update Next Move</button>, <button key='completemove' onClick={()=>setFeedback('Complete Move is preview until move history is modeled.')} className='rounded border border-neon/40 bg-bg px-3 py-1 text-sm'>Complete Move (Preview)</button>, <button key='freeze' onClick={()=>freezeSpark(spark.id)} className='rounded border border-neon/40 bg-bg px-3 py-1 text-sm'>Freeze</button>] : [<button key='output' onClick={()=>setFeedback('Add another output by releasing a new Blaze below.')} className='rounded border border-neon/40 bg-bg px-3 py-1 text-sm'>Add Another Output</button>, <button key='flare' className='rounded border border-neon/40 bg-bg px-3 py-1 text-sm'>Review Solar Flare</button>, <button key='sun' className='rounded border border-neon/40 bg-bg px-3 py-1 text-sm'>Create Sun (Preview)</button>];

  return <Layout><h2 className='text-xl font-semibold'>Spark Command Hub</h2>
    <section className='mt-3 rounded-xl border border-neon/40 bg-panelAlt/85 p-4'><h3 className='text-sm uppercase text-neonDim'>Diagnosis</h3><p className='mt-2 text-sm'>{diagnosis}</p><p className='mt-2 text-xs text-neonDim'>Next command: {heat.suggestedAction}</p></section>
    {feedback?<p className='mt-2 rounded border border-neon/40 p-2 text-sm text-neon'>{feedback}</p>:null}{routeOpen?<section className='mt-3 rounded border border-neon/30 p-3 text-sm'><p className='font-medium'>Route Spark</p><div className='mt-2 grid gap-2 sm:grid-cols-2'><input value={routeType} onChange={(e)=>setRouteType(e.target.value)} placeholder='What is this Spark?' className='rounded bg-bg p-2'/><input value={routePathway} onChange={(e)=>setRoutePathway(e.target.value)} placeholder='Possible output lane' className='rounded bg-bg p-2'/><input value={nextMoveInput} onChange={(e)=>setNextMoveInput(e.target.value)} placeholder='Next physical move' className='rounded bg-bg p-2'/><input value={routeValueTags} onChange={(e)=>setRouteValueTags(e.target.value)} placeholder='Value tags comma-separated' className='rounded bg-bg p-2'/></div><button onClick={()=>{routeSpark(spark.id,{title:routePathway,outputType:routeType,nextMove:nextMoveInput,valueTags:routeValueTags.split(',').map((x)=>x.trim()).filter(Boolean)});setFeedback(`Routed Spark: ${spark.title}`);}} className='mt-2 rounded bg-neon px-3 py-1 text-bg'>Complete Routing</button></section>:null}
    <article className='mt-3 rounded-xl border border-neon/40 bg-panelAlt/85 p-4'><div className='flex items-center justify-between'><h3 className='text-lg font-semibold'>{spark.title}</h3><button onClick={startEdit} className='rounded border border-neon/40 px-3 py-1 text-xs'>Edit Spark</button></div><p className='text-xs text-muted'>{spark.kind} • {branch?.name ?? spark.branchId}</p><p className='mt-2 text-sm'>{spark.notes || 'No notes yet.'}</p>
    <dl className='mt-3 grid grid-cols-2 gap-2 text-sm'><div><dt className='text-muted'>Stage</dt><dd>{spark.stage}</dd></div><div><dt className='text-muted'>Status</dt><dd>{spark.status}</dd></div><div><dt className='text-muted'>What could it become?</dt><dd>{routes.length ? routes.map((r)=>r.title).join(', ') : 'No pathway chosen yet'}</dd></div><div><dt className='text-muted'>Next Physical Move</dt><dd>{spark.nextMove || 'No next move set yet'}</dd></div></dl>
    <div className='mt-3 flex flex-wrap gap-2'>{stageActions}</div>{spark.stage==='Spark'?<div className='mt-3 rounded border border-neon/30 p-3 text-sm'><p className='font-medium'>Post-Capture Decision</p><div className='mt-2 flex flex-wrap gap-2'><button onClick={()=>setRouteOpen((x)=>!x)} className='rounded border border-neon/40 px-2 py-1 text-xs'>Route Now</button><button onClick={()=>setFeedback('Add a pathway below to shape this Spark.')} className='rounded border border-neon/40 px-2 py-1 text-xs'>Add Pathway</button><button onClick={()=>setFeedback('Set your next move in Next Move Command.')} className='rounded border border-neon/40 px-2 py-1 text-xs'>Set Next Move</button><button onClick={()=>freezeSpark(spark.id)} className='rounded border border-neon/40 px-2 py-1 text-xs'>Save for Later / Freeze</button></div></div>:null}</article>

    <section className='mt-4 rounded-xl border border-neon/40 bg-panelAlt/85 p-4'><h4 className='text-sm uppercase text-neonDim'>Next Move Command</h4><div className='mt-2 flex gap-2'><input value={nextMoveInput} onChange={(e)=>setNextMoveInput(e.target.value)} placeholder='Record rough vocals / Clean linework / Export print file...' className='flex-1 rounded bg-bg p-2'/><button className='rounded bg-neon px-3 text-bg' onClick={()=>{if(nextMoveInput.trim()){updateSpark(spark.id,{nextMove:nextMoveInput.trim()});setFeedback(`Set Next Move: ${nextMoveInput.trim()}`);setNextMoveInput('');}}}>Set Next Move</button></div></section>

    <section className='mt-4 rounded-xl border border-neon/40 bg-panelAlt/85 p-4'><h4 className='text-sm uppercase text-neonDim'>Pathways</h4><div className='mt-2 flex gap-2'><input value={lane} onChange={(e)=>setLane(e.target.value)} placeholder='Possible output lane/title' className='flex-1 rounded bg-bg p-2'/><button className='rounded bg-neon px-3 text-bg' onClick={()=>{if(lane.trim()){addPathway(spark.id,lane.trim());setFeedback('Pathway added.');setLane('');}}}>Add Pathway</button></div><ul className='mt-3 space-y-2'>{routes.length?routes.map((r)=>{const readiness=calculatePathwayReadiness(r,spark,{branches,pathways,blazes});return <li key={r.id} className='rounded border border-neon/40 p-3 text-sm'><p className='font-medium'>{r.title}</p><p className='text-xs text-muted'>Status: {r.status} • Readiness: {readiness.label}</p><p className='mt-1 text-xs text-muted'>{readiness.reasons.join(' ')}</p><p className='mt-1 text-xs text-neonDim'>Next move: {spark.nextMove || 'Set one for this pathway.'}</p><div className='mt-2 flex flex-wrap gap-2'><button onClick={()=>updatePathway(r.id,{status:'chosen'})} className='rounded border border-neon/40 px-2 py-1 text-xs'>Choose Pathway</button><button onClick={()=>routes[0] ? activateFire(spark.id, routes[0].id) : { ok: false }} className='rounded border border-neon/40 px-2 py-1 text-xs'>Activate as Fire</button><button onClick={()=>updateSpark(spark.id,{status:'frozen'})} className='rounded border border-neon/40 px-2 py-1 text-xs'>Freeze Pathway (Preview)</button></div></li>}):<li className='text-sm text-muted'>No pathways yet.</li>}</ul></section>

    <section className='mt-4 rounded-xl border border-neon/40 bg-panelAlt/85 p-4'><h4 className='text-sm uppercase text-neonDim'>Release Blaze</h4><div className='mt-2 grid gap-2 sm:grid-cols-2'><input value={outputTitle} onChange={(e)=>setOutputTitle(e.target.value)} placeholder='Output title' className='rounded bg-bg p-2'/><input value={outputType} onChange={(e)=>setOutputType(e.target.value)} placeholder='song/reel/post/tattoo/print...' className='rounded bg-bg p-2'/><select value={releasePathwayId} onChange={(e)=>setReleasePathwayId(e.target.value)} className='rounded bg-bg p-2'><option value=''>Related pathway (optional)</option>{routes.map((r)=><option key={r.id} value={r.id}>{r.title}</option>)}</select><input value={releaseNotes} onChange={(e)=>setReleaseNotes(e.target.value)} placeholder='Optional notes' className='rounded bg-bg p-2'/><button className='rounded bg-neon px-3 py-2 text-bg' onClick={()=>{if(outputTitle.trim()&&outputType.trim()){releaseBlaze(spark.id,outputTitle.trim(),outputType.trim(),releasePathwayId || undefined, releaseNotes.trim() || undefined);setFeedback(`Released Blaze: ${outputTitle.trim()}`);setOutputTitle('');}}}>Release Blaze</button></div></section>

    {editing ? <section className='mt-4 rounded-xl border border-neon/40 bg-panelAlt/85 p-4'><h4 className='text-sm uppercase text-neonDim'>Edit Spark</h4><div className='mt-2 grid gap-2'><input value={draft.title} onChange={(e)=>setDraft({...draft,title:e.target.value})} className='rounded bg-bg p-2'/><input value={draft.kind} onChange={(e)=>setDraft({...draft,kind:e.target.value})} className='rounded bg-bg p-2'/><select value={draft.branchId} onChange={(e)=>setDraft({...draft,branchId:e.target.value})} className='rounded bg-bg p-2'>{branches.map((b)=><option key={b.id} value={b.id}>{b.name}</option>)}</select><textarea value={draft.notes} onChange={(e)=>setDraft({...draft,notes:e.target.value})} className='rounded bg-bg p-2'/><input value={draft.nextMove} onChange={(e)=>setDraft({...draft,nextMove:e.target.value})} className='rounded bg-bg p-2'/><select value={draft.status} onChange={(e)=>setDraft({...draft,status:e.target.value})} className='rounded bg-bg p-2'><option>new</option><option>active</option><option>cooling</option><option>frozen</option></select><details><summary>Advanced</summary><select value={draft.stage} onChange={(e)=>setDraft({...draft,stage:e.target.value})} className='mt-1 rounded bg-bg p-2'><option>Spark</option><option>Ember</option><option>Fire</option><option>Blaze</option></select></details><div className='flex gap-2'><button onClick={()=>{updateSpark(spark.id,draft as any);setEditing(false);setFeedback(`Edited Spark: ${draft.title}`);}} className='rounded bg-neon px-3 py-1 text-bg'>Save</button><button onClick={()=>setEditing(false)} className='rounded border border-neon/40 px-3 py-1'>Cancel</button></div></div></section> : null}

    <section className='mt-4 rounded-xl border border-neon/40 bg-panelAlt/85 p-4'><h4 className='text-sm uppercase text-neonDim'>Attachments</h4><div className='mt-2 grid gap-2 sm:grid-cols-2'>{sparkAttachments.map((att)=><div key={att.id} className='rounded border border-neon/30 p-2 text-xs'><p>{att.name}</p><p className='text-muted'>{att.type} {att.size?`• ${Math.round(att.size/1024)} KB`:''}</p>{att.type==='image'&&att.objectUrl?<img src={att.objectUrl} alt={att.name} className='mt-2 max-h-36 rounded'/>:null}{att.type==='audio'&&att.objectUrl?<audio controls src={att.objectUrl} className='mt-2 w-full'/>:null}{att.type==='video'&&att.objectUrl?<video controls src={att.objectUrl} className='mt-2 max-h-44 w-full rounded'/>:null}{att.type==='link'&&att.linkUrl?<a href={att.linkUrl} className='mt-1 block text-neon underline'>{att.linkUrl}</a>:null}{att.type==='note'?<p className='mt-1 text-sm'>{att.textContent}</p>:null}<button onClick={()=>removeSparkAttachment(att.id)} className='mt-2 rounded border border-neon/40 px-2 py-1'>Remove</button></div>)}</div><div className='mt-3'><input type='file' onChange={(e)=>{const f=e.target.files?.[0]; if(!f)return; const t=f.type.startsWith('image/')?'image':f.type.startsWith('audio/')?'audio':f.type.startsWith('video/')?'video':'file'; addSparkAttachments(spark.id,[{name:f.name,type:t as any,mimeType:f.type,size:f.size,objectUrl:URL.createObjectURL(f)}]);}} className='text-sm'/></div></section>

    <section className='mt-4 rounded-xl border border-neon/40 bg-panelAlt/85 p-4'><h4 className='text-sm uppercase text-neonDim'>Action Log</h4><ul className='mt-2 text-sm'>{actions.filter((a) => a.action.includes(spark.title) || a.action.includes('Next Move') || a.action.includes('Blaze')).slice(0,8).map((a)=><li key={a.id}>{a.date} • {a.action}</li>)}</ul></section>
    <section className='mt-4 rounded-xl border border-neon/40 bg-panelAlt/85 p-4'><h4 className='text-sm uppercase text-neonDim'>Blaze Logs</h4><ul className='mt-2 text-sm'>{sparkBlazes.length?sparkBlazes.map((b)=><li key={b.id}>{b.releasedAt} • {b.title}</li>):<li className='text-muted'>No Blaze Logs yet.</li>}</ul></section>
  </Layout>;
}

