'use client';
import Link from 'next/link';
import { useMemo, useState } from 'react';
import Layout from '@/components/Layout';
import { useStore } from '@/components/store';
import { calculateHeatSignal, getCoolDownWarnings } from '@/lib/logic';

export default function VaultPage() {
  const { sparks, attachments, pathways, branches } = useStore();
  const [stageFilter, setStageFilter] = useState('all');
  const [statusFilter, setStatusFilter] = useState('all');
  const [branchFilter, setBranchFilter] = useState('all');
  const [query, setQuery] = useState('');

  const filteredSparks = useMemo(() => sparks.filter((s) => (stageFilter === 'all' || s.stage === stageFilter) && (statusFilter === 'all' || s.status === statusFilter) && (branchFilter==='all'||s.branchId===branchFilter) && (!query.trim()||s.title.toLowerCase().includes(query.toLowerCase()))), [sparks, stageFilter, statusFilter, branchFilter, query]);
  const warnings = getCoolDownWarnings(sparks, pathways, [], branches);

  return <Layout><h2 className="mb-4 text-xl font-semibold">Vault</h2><div className="mb-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">
<input value={query} onChange={(e)=>setQuery(e.target.value)} className="rounded-lg border border-neon/40 bg-panelAlt/85 px-3 py-2" placeholder="Search assets" /><select aria-label="Asset type" value={stageFilter} onChange={(e) => setStageFilter(e.target.value)} className="rounded-lg border border-neon/40 bg-panelAlt/85 px-3 py-2"><option value="all">All assets</option><option value="Spark">Spark</option><option value="Ember">Ember</option><option value="Flame">Flame</option><option value="Blaze">Blaze</option></select><select aria-label="Lifecycle state" value={statusFilter} onChange={(e) => setStatusFilter(e.target.value)} className="rounded-lg border border-neon/40 bg-panelAlt/85 px-3 py-2"><option value="all">Lifecycle state</option><option value="new">new</option><option value="active">active</option><option value="cooling">cooling</option><option value="frozen">frozen</option><option value="archived">archived</option><option value="killed">killed</option></select><select aria-label="Branch" value={branchFilter} onChange={(e)=>setBranchFilter(e.target.value)} className="rounded-lg border border-neon/40 bg-panelAlt/85 px-3 py-2"><option value='all'>Branch</option>{branches.map((b)=><option key={b.id} value={b.id}>{b.name}</option>)}</select></div>
    {filteredSparks.length === 0 ? <section className="rounded-xl border border-neon/40 bg-panelAlt/85 p-6 text-sm text-muted">No assets match these filters yet. Clear filters or capture a new asset.</section> : <div className='grid gap-3 lg:grid-cols-2'>{filteredSparks.map((s)=>{const branch = branches.find((b) => b.id === s.branchId);const sparkPathways = pathways.filter((p) => p.sparkId === s.id);const nextMove = sparkPathways[0]?.title ? `Advance route: ${sparkPathways[0]?.title}` : 'Add pathway';const heat = calculateHeatSignal(s,{branches,pathways,blazes:[]}); const attachmentTypes=[...new Set(attachments.filter((a)=>a.sparkId===s.id).map((a)=>a.type))];const warning = warnings.find((w)=>w.sparkId===s.id);return <Link key={s.id} href={`/spark/${s.id}`} className="block rounded-xl border border-neon/40 bg-panelAlt/85 p-4 shadow-glow backdrop-blur-sm transition hover:border-neon/70"><p className="text-xs text-muted">{s.kind} • {s.updatedAt}</p><h3 className="mt-1 font-semibold">{s.title.trim() || 'Untitled Spark'}</h3><dl className="mt-2 grid grid-cols-2 gap-2 text-sm"><div><dt className="text-muted">Asset type</dt><dd>{s.kind}</dd></div><div><dt className="text-muted">Branch</dt><dd>{branch?.name ?? s.branchId}</dd></div><div><dt className="text-muted">Lifecycle State</dt><dd>{s.stage}</dd></div><div><dt className="text-muted">Status</dt><dd>{s.status}</dd></div><div><dt className="text-muted">Heat Score</dt><dd>{heat.score} ({heat.label})</dd></div><div className="col-span-2"><dt className="text-muted">Current Objective</dt><dd>{nextMove}</dd></div></dl><p className="mt-2 text-xs text-muted">{heat.reasons[0]} {heat.reasons[3]}</p><p className="mt-1 text-xs text-neonDim">Needs Attention: {heat.suggestedAction}</p><p className='mt-1 text-xs text-muted'>Attachments: {attachmentTypes.length?attachmentTypes.join(', '):'none'}</p>{warning?<p className="mt-2 text-xs text-fire">{warning.reason} {warning.suggestedAction}</p>:null}</Link>;})}</div>}</Layout>;
}
