'use client';
import Link from 'next/link';
import { useMemo, useState } from 'react';
import Layout from '@/components/Layout';
import { useStore } from '@/components/store';
import { derivePriorityChip, getPillarColor, getPillarColorStyles } from '@/lib/ui';

export default function VaultPage() {
  const { sparks, attachments, branches, goals } = useStore();
  const [stageFilter, setStageFilter] = useState('all'); const [statusFilter, setStatusFilter] = useState('all'); const [branchFilter, setBranchFilter] = useState('all'); const [query, setQuery] = useState('');
  const filteredSparks = useMemo(() => sparks.filter((s) => (stageFilter === 'all' || s.stage === stageFilter) && (statusFilter === 'all' || s.status === statusFilter) && (branchFilter==='all'||s.branchId===branchFilter) && (!query.trim()||s.title.toLowerCase().includes(query.toLowerCase()))), [sparks, stageFilter, statusFilter, branchFilter, query]);
  return <Layout><h2 className="mb-4 text-2xl font-semibold tracking-tight">Vault</h2>
    <div className="mb-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><input value={query} onChange={(e)=>setQuery(e.target.value)} className="rounded-lg border border-neon/20 bg-panelAlt/80 px-3 py-2" placeholder="Search assets" /><select value={stageFilter} onChange={(e)=>setStageFilter(e.target.value)} className='rounded-lg border border-neon/20 bg-panelAlt/80 px-3 py-2'><option value='all'>All stages</option><option>Spark</option><option>Ember</option><option>Flame</option><option>Blaze</option></select><select value={statusFilter} onChange={(e)=>setStatusFilter(e.target.value)} className='rounded-lg border border-neon/20 bg-panelAlt/80 px-3 py-2'><option value='all'>All states</option><option>new</option><option>active</option><option>cooling</option><option>frozen</option><option>killed</option></select><select value={branchFilter} onChange={(e)=>setBranchFilter(e.target.value)} className='rounded-lg border border-neon/20 bg-panelAlt/80 px-3 py-2'><option value='all'>Pillar</option>{branches.map((b)=><option key={b.id} value={b.id}>{b.name}</option>)}</select></div>
    {filteredSparks.length===0 ? <section className='rounded-xl border border-neon/20 bg-panelAlt/80 p-6 text-sm text-muted'>No assets match these filters.</section> : <div className='grid gap-3 lg:grid-cols-2'>{filteredSparks.map((s)=>{const branch=branches.find((b)=>b.id===s.branchId); const st=getPillarColorStyles(getPillarColor(branch)); const attachmentCount=attachments.filter((a)=>a.sparkId===s.id).length; const currentGoal=goals.find((g)=>g.id===s.goalId || (g.currentAction && s.currentAction && g.currentAction===s.currentAction)); const priority=derivePriorityChip(s,goals); return <article key={s.id} className={`rounded-xl border border-neon/15 bg-panelAlt/75 p-4 ${st.border} ${st.glow}`}><p className='text-xs text-muted'>{s.kind}</p><h3 className='mt-1 font-semibold'>{s.title}</h3><div className='mt-2 flex flex-wrap gap-2 text-xs'><span className={`rounded-full border px-2 py-0.5 ${st.chip}`}>{branch?.name ?? 'Pillar'}</span><span className='rounded-full border border-neon/30 px-2 py-0.5'>{s.stage}</span><span className='rounded-full border border-neon/30 px-2 py-0.5'>{priority}</span>{s.scheduleBucket?<span className='rounded-full border border-neon/20 px-2 py-0.5'>Schedule: {s.scheduleBucket}</span>:null}{attachmentCount?<span className='rounded-full border border-neon/20 px-2 py-0.5'>📎 {attachmentCount}</span>:null}</div><div className='mt-2 text-xs text-muted'>{currentGoal?<p>Goal: {currentGoal.title}</p>:null}{s.currentAction?<p>Current Action: {s.currentAction}</p>:null}</div><div className='mt-3 flex gap-2 text-xs'><Link href={`/spark/${s.id}`} className='rounded border border-neon/30 px-2 py-1'>Open</Link><Link href={`/spark/${s.id}`} className='rounded border border-neon/30 px-2 py-1'>Edit</Link></div></article>;})}</div>}</Layout>;
}
