'use client';
import Link from 'next/link';
import { useMemo, useState } from 'react';
import Layout from '@/components/Layout';
import { useStore } from '@/components/store';

export default function VaultPage() {
  const { sparks, attachments, branches, goals } = useStore();
  const [stageFilter, setStageFilter] = useState('all');
  const [statusFilter, setStatusFilter] = useState('all');
  const [branchFilter, setBranchFilter] = useState('all');
  const [query, setQuery] = useState('');

  const filteredSparks = useMemo(() => sparks.filter((s) => (stageFilter === 'all' || s.stage === stageFilter) && (statusFilter === 'all' || s.status === statusFilter) && (branchFilter==='all'||s.branchId===branchFilter) && (!query.trim()||s.title.toLowerCase().includes(query.toLowerCase()))), [sparks, stageFilter, statusFilter, branchFilter, query]);
  return <Layout><h2 className="mb-4 text-2xl font-semibold tracking-tight">Vault</h2><div className="mb-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">
<input value={query} onChange={(e)=>setQuery(e.target.value)} className="rounded-lg border border-neon/20 bg-panelAlt/80 px-3 py-2" placeholder="Search assets" /><select aria-label="Asset type" value={stageFilter} onChange={(e) => setStageFilter(e.target.value)} className="rounded-lg border border-neon/20 bg-panelAlt/80 px-3 py-2"><option value="all">All stages</option><option value="Spark">Spark</option><option value="Ember">Ember</option><option value="Flame">Flame</option><option value="Blaze">Blaze</option></select><select aria-label="Lifecycle state" value={statusFilter} onChange={(e) => setStatusFilter(e.target.value)} className="rounded-lg border border-neon/20 bg-panelAlt/80 px-3 py-2"><option value="all">All states</option><option value="new">new</option><option value="active">active</option><option value="cooling">cooling</option><option value="frozen">frozen</option><option value="archived">archived</option><option value="killed">killed</option></select><select aria-label="Pillar" value={branchFilter} onChange={(e)=>setBranchFilter(e.target.value)} className="rounded-lg border border-neon/20 bg-panelAlt/80 px-3 py-2"><option value='all'>Pillar</option>{branches.map((b)=><option key={b.id} value={b.id}>{b.name}</option>)}</select></div>
    {filteredSparks.length === 0 ? <section className="rounded-xl border border-neon/20 bg-panelAlt/80 p-6 text-sm text-muted">No assets match these filters yet.</section> : <div className='grid gap-3 lg:grid-cols-2'>{filteredSparks.map((s)=>{const branch = branches.find((b) => b.id === s.branchId);const attachmentCount=attachments.filter((a)=>a.sparkId===s.id).length;const currentGoal = goals.find((g)=>g.currentAction && s.currentAction && g.currentAction===s.currentAction);return <article key={s.id} className={`rounded-xl border bg-panelAlt/75 p-4 transition ${s.status==='new'?'border-amber-300/40 shadow-[0_0_18px_rgba(251,191,36,0.18)]':'border-neon/20'}`}><p className="text-xs text-muted">{s.kind} • {branch?.name ?? 'Pillar'}</p><h3 className="mt-1 font-semibold">{s.title.trim() || 'Untitled Spark'}</h3><div className='mt-2 flex flex-wrap gap-2 text-xs'><span className='rounded-full border border-neon/30 px-2 py-0.5'>{s.stage}</span><span className='rounded-full border border-neon/20 px-2 py-0.5'>{s.status}</span>{s.scheduleBucket?<span className='rounded-full border border-neon/20 px-2 py-0.5'>Schedule: {s.scheduleBucket}</span>:null}{attachmentCount?<span className='rounded-full border border-neon/20 px-2 py-0.5'>📎 {attachmentCount}</span>:null}</div><div className='mt-2 space-y-1 text-xs text-muted'>{currentGoal?<p>Goal: {currentGoal.title}</p>:null}{s.currentAction?<p>Current Action: {s.currentAction}</p>:null}</div><div className='mt-3 flex gap-2 text-xs'><Link href={`/spark/${s.id}`} className='rounded border border-neon/30 px-2 py-1 hover:border-neon/60'>Open</Link><Link href={`/spark/${s.id}`} className='rounded border border-neon/30 px-2 py-1 hover:border-neon/60'>Edit</Link></div></article>;})}</div>}</Layout>;
}
